In [1]:
import pandas as pd
import numpy as np

In [2]:
#Creamos una lista de dos dimensiones
a=[[11,12,13],[21,22,23],[31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
#Podemos ver las dimensiones con ndim
A.ndim

2

In [6]:
#Podemos ver la forma con shape
A.shape

(3, 3)

In [7]:
#La cantidad de valores con size
A.size

9

In [8]:
#Suma matricial
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]])
Z=X+Y
Z

array([[3, 1],
       [1, 3]])

In [9]:
#Multiplicación por un escalar
Y=np.array([[2,1],[1,2]])
Z=2*Y
Z

array([[4, 2],
       [2, 4]])

In [10]:
#Multiplicación por otra matriz
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]])
Z=X*Y
Z 

array([[2, 0],
       [0, 2]])

In [12]:
#Multiplicación por otra matriz, diferentes dimensiones
A=np.array([[0,1,1],[1,0,1]])
B=np.array([[1,1],[1,1],[-1,1]])
C=np.dot(A,B)
C

array([[0, 2],
       [0, 2]])